POST  http://localhost:4000/api/newBooking
Content-Type: application/json

{
    "NOG": "996",
    "phone": "7666666",
    "tableId": "632634f4adb44440450d39ed",
    "time": "21:00"
}

###

GET  http://localhost:4000/api/bookings